global class PropertyWrapper {
    public String city;
    public String country;
    public String countryCode;
    public String estMaxPrice;
    public String estMinPrice;
    public String latitude;
    public String longitude;
    public Boolean hasSold;
    public Integer landSize;
    public String mainImageUrl;
    public String name;
    public Integer noOfBathrooms;
    public Integer noOfRooms;
    public String postalcode;
    public String salesforceId;
    public Integer soldPrice;
    public String state;
    public String street;
    public String suburb;
    public String uuid;
}